In [1]:
import pandas as pd

In [2]:
train_df = pd.read_parquet("data/df_train_preprocessed.parquet")
train_df.drop(columns=["month_decision", "weekday_decision", "year_decision", "WEEK_NUM", "case_id"], inplace=True)
train_df.shape

(1088836, 199)

In [3]:
train_df

,target,assignmentdate_238D,birthdate_574D,dateofbirth_337D,days120_123L,days30_165L,description_5085714M,education_1103M,maritalst_385M,pmtaverage_3A,...,price_1097A_missing,twobodfilling_608L_missing,max_byoccupationinc_3656910L_missing,max_credlmt_230A_missing,max_credlmt_935A_missing,max_outstandingamount_362A_missing,max_numberofoverdueinstlmaxdat_641D_missing,max_annualeffectiverate_199L_missing,max_annualeffectiverate_63L_missing,max_amount_416A_missing
0,0,0.077125,0.091781,0.125197,-0.310926,-0.565845,-6.409159,-2.173400,-2.411442,-0.129158,...,1,0,1,1,1,1,1,1,1,1
1,0,0.077125,0.091781,0.125197,-0.310926,-0.565845,-6.409159,-2.173400,-2.411442,-0.129158,...,1,0,1,1,1,1,1,1,1,1
2,0,0.077125,0.091781,0.125197,-0.310926,-0.565845,-6.409159,-2.173400,-2.411442,-0.129158,...,1,0,1,1,1,1,1,1,1,1
3,0,0.077125,0.091781,0.125197,-0.310926,-0.565845,-6.409159,-2.173400,-2.411442,-0.129158,...,1,0,1,1,1,1,1,1,1,1
4,1,0.077125,0.091781,0.125197,-0.310926,-0.565845,-6.409159,-2.173400,-2.411442,-0.129158,...,1,0,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1479675,0,0.077125,0.091781,-0.147920,0.230528,-0.565845,0.156027,-0.702132,-0.029897,-0.129158,...,1,0,1,1,1,0,1,1,1,1
1479676,0,0.077125,0.091781,0.656487,3.479255,2.010193,0.156027,0.797013,0.821998,-0.129158,...,1,0,1,0,0,0,1,1,1,1
1479677,0,0.077125,0.091781,-1.736807,1.313437,-0.565845,0.156027,-0.702132,-0.029897,-0.129158,...,1,0,0,1,1,0,1,1,0,1
1479678,0,0.077125,0.091781,1.051976,-0.852381,-0.565845,0.156027,0.797013,0.821998,-0.129158,...,0,0,1,1,1,1,1,1,1,1
1479679,0,0.077125,0.091781,-2.101540,0.230528,0.722174,0.156027,-1.743068,-2.183171,-0.129158,...,1,0,0,0,1,0,1,1,0,1

In [4]:
cols = [col for col in train_df.columns if col != 'target']

cols_df = pd.DataFrame({'column_name': cols})

display(cols_df)

                                     column_name
0                            assignmentdate_238D
1                                 birthdate_574D
2                               dateofbirth_337D
3                                   days120_123L
4                                    days30_165L
..                                           ...
193           max_outstandingamount_362A_missing
194  max_numberofoverdueinstlmaxdat_641D_missing
195         max_annualeffectiverate_199L_missing
196          max_annualeffectiverate_63L_missing
197                      max_amount_416A_missing

[198 rows x 1 columns]

In [5]:
df_raw = pd.read_parquet("data/df_train_full_raw.parquet")

In [6]:
df_raw

,case_id,WEEK_NUM,target,month_decision,weekday_decision,year_decision,assignmentdate_238D,assignmentdate_4527235D,assignmentdate_4955616D,birthdate_574D,...,max_subjectroles_name_541M,max_subjectroles_name_838M,max_collater_valueofguarantee_1124L,max_collater_valueofguarantee_876L,max_pmts_month_158T,max_pmts_month_706T,max_pmts_year_1139T,max_pmts_year_507T,max_num_group1_13,max_num_group2_13
0,0,0,0,1,4,2019,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0,0,1,4,2019,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0,0,1,5,2019,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,0,0,1,4,2019,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,0,1,1,5,2019,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1526654,2703450,91,0,10,1,2020,NaN,NaN,-998.0,NaN,...,ab3c25cf,ab3c25cf,0.0,0.0,12.0,12.0,2021.0,2021.0,10.0,35.0
1526655,2703451,91,0,10,1,2020,NaN,NaN,-5591.0,NaN,...,ab3c25cf,ab3c25cf,0.0,0.0,12.0,12.0,2021.0,2021.0,3.0,23.0
1526656,2703452,91,0,10,1,2020,NaN,NaN,NaN,NaN,...,ab3c25cf,ab3c25cf,0.0,0.0,12.0,12.0,2021.0,2020.0,2.0,35.0
1526657,2703453,91,0,10,1,2020,NaN,NaN,-4616.0,NaN,...,ab3c25cf,ab3c25cf,0.0,0.0,12.0,12.0,2021.0,2020.0,12.0,35.0
1526658,2703454,91,0,10,1,2020,NaN,NaN,-7349.0,NaN,...,ab3c25cf,ab3c25cf,0.0,176000.0,12.0,12.0,2021.0,2021.0,8.0,35.0